name: CI/CD - OpenFaaS

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install faas-cli
        run: curl -sLS https://cli.openfaas.com | sudo sh

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build function
        run: faas-cli build -f stack.yaml

      - name: Push image
        run: faas-cli push -f stack.yaml

      - name: Login to OpenFaaS
        run: |
          echo "${{ secrets.OPENFAAS_PASSWORD }}" | faas-cli login \
          --gateway ${{ secrets.OPENFAAS_URL }} \
          --username ${{ secrets.OPENFAAS_USERNAME }} \
          --password-stdin

      - name: Deploy function
        run: faas-cli deploy -f stack.yaml --gateway ${{ secrets.OPENFAAS_URL }}
